### PR TITLE
Better argument handling and changes to filter argument

### PR DESCRIPTION
**Pull request by HeavenVolkoff**
Hi,
I saw your pull request (great job by the way) and as it is still open I thought it would be better to merge this changes to your fork instead of opening another one at @syscl repo.

I implemented a better way to parse the command line arguments using `getopt_long`.
I also changed the argument of `--filter`, basically I removed the `eventMessage CONTAINS[c] \"` from the code, because I think this way it allows us to use any kind of predicate, instead of just the `eventMessage`.
And I modified the help message

### CODE REVIEW

**Comment by MuntashirAkon** [comment]
(y)
I did comment that I was being lazy (actually I had a semester final exam to attend).
Nice cleanup, by the way!

**Comment by MuntashirAkon** [comment]
The idea behind `eventMessage CONTAINS[c] \"%s\"` was: I frequently need to filter logs by `eventMessage` (for example, I needed to find all the logs containing `[IGPU]`).
BTW, the new filter method would be hard for any body who don't know anything about predicate.

**Comment by HeavenVolkoff** [comment]
Thanks for accepting the PR,
About `--filter`, I, personally, think it would be best to not restraint the command, but I do understand that it would be hard to anyone that is not conversant with predicates. Maybe we could put some info on the helper or we could add a `--filterMessage` option?

**Comment by MuntashirAkon** [comment]
Yes, we can. It's convenient for many purposes, specially for debugging.

**Pull request merged**
